### ISSUE TITLE
kube-etcd-network-checkpointer runs without self-hosted etcd

### ISSUE THREAD

**Issue by bzub** [poseidon/bootkube-terraform#14]
It appears that bootkube normally omits this DaemonSet when not using self-hosted etcd.

**Comment by bzub** [comment]
It could have some benefit even outside of self-hosted etcd. Not sure yet.

**Comment by dghubble** [comment]
I recall leaving it there bc it was harmless, but it isn't needed with on-host etcd. The module could be changed to add it only if self-hosted etcd is chosen.
